import { z } from 'zod'
import { gridViewSchema, trackerSchema } from './tracker'

export const managerSchema = z
  .object({
    thinking: z.string().optional().describe('Detailed thinking process or internal monologue of the manager'),
    prd: z
      .object({
        name: z.string().optional().describe('Short name for the tracker'),
        description: z.string().optional().describe('Short description of the tracker'),
        keyFeatures: z.array(z.string()).optional().describe('List of key features or goals'),
      })
      .partial()
      .optional()
      .describe('The Product Requirements Document generated by the manager'),
    builderTodo: z
      .array(
        z
          .object({
            task: z.string().optional().describe('The distinct task to perform (e.g., "Change grouping to Priority")'),
            target: z.string().optional().describe('The name of the item to change (e.g., "Tasks Grid")'),
            action: z.string().optional().describe('The action to take (e.g., create/update/delete/ignore)'),
          })
          .passthrough(),
      )
      .optional()
      .describe('Todo list for the Builder Agent to execute. Derived from comparing the User Request with the Previous Tracker.'),
  })
  .passthrough()

const patchConfigSchema = z.record(z.string(), z.any()).optional()

const tabPatchSchema = z
  .object({
    id: z.string(),
    name: z.string().optional(),
    placeId: z.coerce.number().optional(),
    config: patchConfigSchema,
    _delete: z.boolean().optional(),
  })
  .passthrough()

const sectionPatchSchema = z
  .object({
    id: z.string(),
    name: z.string().optional(),
    tabId: z.string().optional(),
    placeId: z.coerce.number().optional(),
    config: patchConfigSchema,
    _delete: z.boolean().optional(),
  })
  .passthrough()

const gridPatchSchema = z
  .object({
    id: z.string(),
    name: z.string().optional(),
    sectionId: z.string().optional(),
    placeId: z.coerce.number().optional(),
    config: patchConfigSchema,
    views: z.array(gridViewSchema).optional(),
    _delete: z.boolean().optional(),
  })
  .passthrough()

const fieldPatchSchema = z
  .object({
    id: z.string(),
    dataType: z.string().optional(),
    ui: z
      .object({
        label: z.string().optional(),
        placeholder: z.string().optional(),
      })
      .partial()
      .optional(),
    config: patchConfigSchema,
    _delete: z.boolean().optional(),
  })
  .passthrough()

const renderAsEnum = z.enum(['default', 'table', 'kanban', 'calendar', 'timeline']).optional()

const layoutNodePatchSchema = z
  .object({
    gridId: z.string(),
    fieldId: z.string(),
    order: z.coerce.number().optional(),
    renderAs: renderAsEnum,
    _delete: z.boolean().optional(),
  })
  .passthrough()

export const trackerPatchSchema = z
  .object({
    tabs: z.array(tabPatchSchema).optional(),
    sections: z.array(sectionPatchSchema).optional(),
    grids: z.array(gridPatchSchema).optional(),
    fields: z.array(fieldPatchSchema).optional(),
    layoutNodes: z.array(layoutNodePatchSchema).optional(),
    bindings: z.record(z.string(), z.any()).optional(),
    bindingsRemove: z.array(z.string()).optional(),
    validations: z.record(z.string(), z.any()).optional(),
    validationsRemove: z.array(z.string()).optional(),
    calculations: z.record(z.string(), z.any()).optional(),
    calculationsRemove: z.array(z.string()).optional(),
    dependsOn: z.array(z.any()).optional(),
    /** Patch style overrides keyed by grid/view id. Set a key to null to remove it. */
    styles: z.record(z.string(), z.any()).optional(),
    /** Array of grid/view ids whose style overrides should be removed. */
    stylesRemove: z.array(z.string()).optional(),
  })
  .passthrough()

export const multiAgentSchema = z
  .object({
    manager: managerSchema.optional(),
    tracker: trackerSchema.optional(),
    trackerPatch: trackerPatchSchema.optional(),
  })
  .passthrough()

export type MultiAgentSchema = z.infer<typeof multiAgentSchema>
export type TrackerPatchSchema = z.infer<typeof trackerPatchSchema>
