import { z } from 'zod'
import { trackerSchema } from './tracker'

export const managerSchema = z.object({
  thinking: z.string().describe('Detailed thinking process or internal monologue of the manager'),
  prd: z.object({
    name: z.string().describe('The name of the tracker'),
    description: z.string().describe('Short description of the tracker'),
    keyFeatures: z.array(z.string()).describe('List of key features or goals'),
    structure: z.string().describe('High-level overview of the tabs and components envisioned'),
  }).describe('The Product Requirements Document generated by the manager')
})

export const multiAgentSchema = z.object({
  manager: managerSchema.optional(),
  tracker: trackerSchema.optional()
})

export type MultiAgentSchema = z.infer<typeof multiAgentSchema>
