import { z } from 'zod'
import { trackerSchema } from './tracker'

export const managerSchema = z.object({
  thinking: z.string().describe('Detailed thinking process or internal monologue of the manager'),
  prd: z.object({
    name: z.string().describe('The name of the tracker'),
    description: z.string().describe('Short description of the tracker'),
    keyFeatures: z.array(z.string()).describe('List of key features or goals'),
    structure: z.string().describe('High-level overview of the tabs and components envisioned'),
  }).describe('The Product Requirements Document generated by the manager'),
  builderTodo: z.array(z.object({
    task: z.string().describe('The distinct task to perform (e.g., "Change grouping to Priority")'),
    target: z.string().describe('The name of the item to change (e.g., "Tasks Grid")'),
    action: z.enum(['create', 'update', 'delete', 'ignore']).describe('The action to take')
  })).optional().describe('A strict Todo list for the Builder Agent to execute. Derived from comparing the User Request with the Previous Tracker.')
})

export const multiAgentSchema = z.object({
  manager: managerSchema.optional(),
  tracker: trackerSchema.optional()
})

export type MultiAgentSchema = z.infer<typeof multiAgentSchema>
